# Generated by Django 5.2.14 on 2026-05-18 20:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('generated_cards', models.JSONField(default=list)),
                ('cards_accepted', models.IntegerField(default=0)),
                ('ai_provider', models.CharField(default='cerebras', max_length=80)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('provider', models.CharField(default='cerebras', max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=160, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('generation_type', models.CharField(default='text', max_length=40)),
                ('input_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generations', to='decks.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'a_i_generations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='a_i_generat_user_id_dd7225_idx'), models.Index(fields=['status'], name='a_i_generat_status_f281ce_idx'), models.Index(fields=['created_at'], name='a_i_generat_created_a01653_idx')],
            },
        ),
    ]
