# Generated by Django 5.2.14 on 2026-05-18 20:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_review_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('rating', models.CharField(choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], max_length=20)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='decks.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['user', 'reviewed_at'], name='reviews_user_id_c31ae6_idx'), models.Index(fields=['card'], name='reviews_card_id_87476e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interval_minutes', models.IntegerField(default=0)),
                ('next_review_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=3)),
                ('repetition_count', models.IntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to='decks.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_states',
                'indexes': [models.Index(fields=['user'], name='review_stat_user_id_9eabd5_idx'), models.Index(fields=['next_review_at'], name='review_stat_next_re_75e754_idx'), models.Index(fields=['last_synced_at'], name='review_stat_last_sy_9bc315_idx'), models.Index(fields=['updated_at'], name='review_stat_updated_03f8e8_idx')],
                'unique_together': {('card', 'user')},
            },
        ),
    ]
