# Generated by Django 5.2.14 on 2026-05-18 20:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('master_verbs', 'Master verbs'), ('finish_review', 'Finish review'), ('audio_practice', 'Audio practice'), ('daily_goal', 'Daily goal')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('target_count', models.IntegerField()),
                ('current_count', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'indexes': [models.Index(fields=['user', 'date'], name='challenges_user_id_280137_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cards_reviewed', models.IntegerField(default=0)),
                ('study_duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_streaks',
                'indexes': [models.Index(fields=['user', 'date'], name='daily_strea_user_id_387d74_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
